acme_store:
    resource: "@AcmeStoreBundle/Controller/StoreController.php"
    type:     annotation
    prefix:   /store

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
_blog:
    resource: "@AcmeBlogBundle/Controller/BlogController.php"
    type:     annotation
    prefix:   /blog