acme_hello_homepage:
    pattern:  /bonjour/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }
    
acme_another_page:
    pattern: /another/{id}
    defaults: { _controller: AcmeHelloBundle:Hello:another }
